import type {
  Partner,
  Contact,
  SalesTask,
  Quote,
  CrmNotification,
  Operation,
  Interaction,
  CustomerHistoryEvent,
  SalesEvent,
  AutomationEvent,
  ApiConnectionStatus,
  SalesPipeline,
} from "./types";

const today = new Date();
const offset = (days: number) => {
  const d = new Date(today);
  d.setDate(d.getDate() + days);
  return d.toISOString().slice(0, 10);
};

export const seedPartners: Partner[] = [
  {
    id: "p1",
    companyName: "Acme Logistics S.A.",
    tradeName: "Acme",
    taxId: "30-12345678-9",
    country: "Argentina",
    city: "Buenos Aires",
    state: "CABA",
    address: "Av. Corrientes 1234",
    postalCode: "C1043",
    phones: ["+54 11 4321-0000"],
    emails: ["info@acme-logistics.com"],
    website: "https://acme-logistics.com",
    language: "es",
    status: "active",
    salesperson: "Maria Lopez",
    manager: "Carlos Diaz",
    roles: ["customer", "supplier"],
    notes: "Top tier account. Quarterly QBR scheduled.",
    bankDetails: [
      { id: "b1", bankName: "Banco Galicia", accountNumber: "0010-0001-2222", currency: "USD" },
    ],
    branches: [
      { id: "br1", name: "Main HQ", address: "Av. Corrientes 1234", type: "branch" },
      { id: "br2", name: "Ezeiza Warehouse", address: "Ruta 205 km 5", type: "warehouse" },
    ],
    createdAt: offset(-120),
  },
  {
    id: "p2",
    companyName: "Global Freight Partners LLC",
    tradeName: "GFP",
    taxId: "EIN-88-1122334",
    country: "USA",
    city: "Miami",
    state: "FL",
    phones: ["+1 305 555 0199"],
    emails: ["sales@gfp.com"],
    status: "prospect",
    salesperson: "Juan Smith",
    roles: ["customer"],
    bankDetails: [],
    branches: [],
    createdAt: offset(-30),
  },
  {
    id: "p3",
    companyName: "Andes Cargo SRL",
    taxId: "30-99887766-1",
    country: "Chile",
    city: "Santiago",
    phones: ["+56 2 2890 1100"],
    emails: ["contacto@andescargo.cl"],
    status: "active",
    salesperson: "Maria Lopez",
    roles: ["supplier"],
    bankDetails: [],
    branches: [],
    createdAt: offset(-200),
  },
  {
    id: "p4",
    companyName: "Mediterranean Trade Co.",
    country: "Spain",
    city: "Barcelona",
    phones: ["+34 93 555 7788"],
    emails: ["hello@medtrade.es"],
    status: "lead",
    salesperson: "Juan Smith",
    roles: ["other"],
    bankDetails: [],
    branches: [],
    createdAt: offset(-10),
  },
];

export const seedContacts: Contact[] = [
  {
    id: "c1",
    partnerId: "p1",
    firstName: "Lucia",
    lastName: "Fernandez",
    position: "Procurement Manager",
    email: "lucia@acme-logistics.com",
    phone: "+54 11 4321-0001",
  },
  {
    id: "c2",
    partnerId: "p1",
    firstName: "Pablo",
    lastName: "Gomez",
    position: "CFO",
    email: "pablo@acme-logistics.com",
  },
  {
    id: "c3",
    partnerId: "p2",
    firstName: "Sarah",
    lastName: "Mitchell",
    position: "VP Sales",
    email: "sarah@gfp.com",
    phone: "+1 305 555 0188",
  },
  {
    id: "c4",
    partnerId: "p3",
    firstName: "Diego",
    lastName: "Soto",
    position: "Owner",
    email: "diego@andescargo.cl",
  },
];

export const seedTasks: SalesTask[] = [
  {
    id: "t1",
    partnerId: "p1",
    contactId: "c1",
    email: "lucia@acme-logistics.com",
    subject: "Follow up on Q4 freight contract",
    comment: "Send updated tariff sheet and confirm volume estimates.",
    responsibleUser: "Maria Lopez",
    salesperson: "Maria Lopez",
    createdAt: offset(-3),
    dueDate: offset(1),
    dueTime: "10:30",
    priority: "high",
    status: "pending",
    contactMethod: "call",
    quoteId: "q1",
    nextContactDate: offset(1),
  },
  {
    id: "t2",
    partnerId: "p2",
    contactId: "c3",
    subject: "Intro call — discovery",
    responsibleUser: "Juan Smith",
    salesperson: "Juan Smith",
    createdAt: offset(-1),
    dueDate: offset(-2),
    dueTime: "14:00",
    priority: "urgent",
    status: "pending",
    contactMethod: "call",
    transactionId: "op3",
    nextContactDate: offset(1),
  },
  {
    id: "t3",
    partnerId: "p3",
    subject: "Renew supplier agreement",
    responsibleUser: "Maria Lopez",
    salesperson: "Maria Lopez",
    createdAt: offset(-7),
    dueDate: offset(5),
    priority: "medium",
    status: "in_progress",
    contactMethod: "email",
    nextContactDate: offset(5),
  },
  {
    id: "t4",
    partnerId: "p1",
    subject: "Send quarterly report",
    responsibleUser: "Carlos Diaz",
    salesperson: "Maria Lopez",
    createdAt: offset(-14),
    dueDate: offset(-5),
    priority: "low",
    status: "completed",
    contactMethod: "email",
    nextContactDate: offset(-1),
  },
  {
    id: "t5",
    partnerId: "p4",
    subject: "Qualify lead — Mediterranean Trade",
    responsibleUser: "Juan Smith",
    salesperson: "Juan Smith",
    createdAt: offset(0),
    dueDate: offset(3),
    priority: "medium",
    status: "pending",
    contactMethod: "whatsapp",
    nextContactDate: offset(3),
  },
];

export const SALESPEOPLE = ["Maria Lopez", "Juan Smith", "Carlos Diaz"];

export const seedQuotes: Quote[] = [
  {
    id: "q1",
    number: "Q-2034",
    partnerId: "p1",
    contactId: "c1",
    subject: "Q4 freight contract — Buenos Aires / Miami",
    status: "sent",
    currency: "USD",
    amount: 48500,
    issueDate: offset(-7),
    validUntil: offset(14),
    salesperson: "Maria Lopez",
    notes: "Awaiting volume confirmation.",
    lines: [
      { id: "ql1", description: "Ocean freight 40HC", quantity: 10, unitPrice: 3800 },
      { id: "ql2", description: "Customs clearance", quantity: 10, unitPrice: 1050 },
    ],
    createdAt: offset(-7),
  },
  {
    id: "q2",
    number: "Q-2035",
    partnerId: "p2",
    contactId: "c3",
    subject: "Pilot shipment quotation",
    status: "draft",
    currency: "USD",
    amount: 9200,
    issueDate: offset(-1),
    validUntil: offset(20),
    salesperson: "Juan Smith",
    lines: [{ id: "ql3", description: "Air freight 500kg MIA-EZE", quantity: 1, unitPrice: 9200 }],
    createdAt: offset(-1),
  },
  {
    id: "q3",
    number: "Q-2030",
    partnerId: "p3",
    subject: "Supplier service renewal",
    status: "won",
    currency: "USD",
    amount: 15400,
    issueDate: offset(-45),
    validUntil: offset(-15),
    salesperson: "Maria Lopez",
    lines: [{ id: "ql4", description: "Annual handling agreement", quantity: 1, unitPrice: 15400 }],
    createdAt: offset(-45),
  },
  {
    id: "q4",
    number: "Q-2028",
    partnerId: "p4",
    subject: "Initial proposal — Med routes",
    status: "lost",
    currency: "EUR",
    amount: 22000,
    issueDate: offset(-60),
    validUntil: offset(-30),
    salesperson: "Juan Smith",
    notes: "Lost to incumbent on price.",
    lines: [
      { id: "ql5", description: "Combined logistics package", quantity: 1, unitPrice: 22000 },
    ],
    createdAt: offset(-60),
  },
];

export const seedNotifications: CrmNotification[] = [
  {
    id: "n1",
    title: "Quote expiring soon",
    message:
      "Q-2034 for Acme Logistics expires in 14 days. Confirm volume assumptions before renewal.",
    type: "reminder",
    severity: "warning",
    createdAt: offset(-1),
    partnerId: "p1",
    quoteId: "q1",
    assignedTo: "Maria Lopez",
  },
  {
    id: "n2",
    title: "Overdue discovery call",
    message: "The intro call with Global Freight Partners is overdue and needs follow-up today.",
    type: "alert",
    severity: "critical",
    createdAt: offset(-2),
    partnerId: "p2",
    taskId: "t2",
    assignedTo: "Juan Smith",
  },
  {
    id: "n3",
    title: "Lead entered workflow",
    message: "Mediterranean Trade Co. was classified as a lead and is waiting for qualification.",
    type: "workflow",
    severity: "info",
    createdAt: offset(0),
    partnerId: "p4",
    taskId: "t5",
    assignedTo: "Juan Smith",
  },
  {
    id: "n4",
    title: "Supplier renewal completed",
    message:
      "Andes Cargo supplier renewal was marked as won and archived in the commercial history.",
    type: "system",
    severity: "success",
    createdAt: offset(-4),
    readAt: offset(-3),
    partnerId: "p3",
    quoteId: "q3",
    assignedTo: "Maria Lopez",
  },
];

export const seedOperations: Operation[] = [
  {
    id: "op1",
    number: "OP-8910",
    partnerId: "p1",
    quoteId: "q1",
    trafficMode: "ocean",
    origin: "Buenos Aires",
    destination: "Miami",
    status: "active",
    openedAt: offset(-5),
    revenue: 48500,
    currency: "USD",
    assignedTo: "Maria Lopez",
  },
  {
    id: "op2",
    number: "OP-8872",
    partnerId: "p3",
    quoteId: "q3",
    trafficMode: "warehouse",
    origin: "Santiago",
    destination: "Santiago DC",
    status: "completed",
    openedAt: offset(-40),
    closedAt: offset(-12),
    revenue: 15400,
    currency: "USD",
    assignedTo: "Maria Lopez",
  },
  {
    id: "op3",
    number: "OP-8924",
    partnerId: "p2",
    quoteId: "q2",
    trafficMode: "air",
    origin: "Miami",
    destination: "Ezeiza",
    status: "on_hold",
    openedAt: offset(-2),
    revenue: 9200,
    currency: "USD",
    assignedTo: "Juan Smith",
  },
];

export const seedInteractions: Interaction[] = [
  {
    id: "i1",
    partnerId: "p1",
    contactId: "c1",
    quoteId: "q1",
    channel: "email",
    direction: "outbound",
    subject: "Updated tariff sheet sent",
    body: "Shared revised ocean freight rates and asked for volume confirmation.",
    occurredAt: offset(-1),
    createdBy: "Maria Lopez",
  },
  {
    id: "i2",
    partnerId: "p2",
    contactId: "c3",
    taskId: "t2",
    channel: "call",
    direction: "outbound",
    subject: "Discovery call attempt",
    body: "Left voicemail and sent a follow-up email with available meeting times.",
    occurredAt: offset(-2),
    createdBy: "Juan Smith",
  },
  {
    id: "i3",
    partnerId: "p4",
    channel: "whatsapp",
    direction: "inbound",
    subject: "Mediterranean route inquiry",
    body: "Prospect asked for route options and transit time estimates.",
    occurredAt: offset(0),
    createdBy: "Juan Smith",
  },
];

export const seedHistoryEvents: CustomerHistoryEvent[] = [
  {
    id: "h1",
    partnerId: "p1",
    type: "quote",
    title: "Quote Q-2034 sent",
    description: "Commercial proposal sent for Q4 freight contract.",
    occurredAt: offset(-7),
    actor: "Maria Lopez",
    quoteId: "q1",
  },
  {
    id: "h2",
    partnerId: "p1",
    type: "operation",
    title: "Operation OP-8910 opened",
    description: "Ocean operation created from accepted shipment plan.",
    occurredAt: offset(-5),
    actor: "SDC Cargo API",
    operationId: "op1",
  },
  {
    id: "h3",
    partnerId: "p2",
    type: "task",
    title: "Discovery task became overdue",
    description: "System flagged overdue follow-up for Global Freight Partners.",
    occurredAt: offset(-2),
    actor: "Alert engine",
    taskId: "t2",
  },
  {
    id: "h4",
    partnerId: "p4",
    type: "status_change",
    title: "Commercial status changed to lead",
    description: "Mediterranean Trade Co. entered the qualification workflow.",
    occurredAt: offset(0),
    actor: "Juan Smith",
  },
];

export const seedSalesEvents: SalesEvent[] = [
  {
    id: "se1",
    partnerId: "p1",
    taskId: "t1",
    quoteId: "q1",
    contactId: "c1",
    kind: "follow_up",
    action: "Quoted shipment options and requested confirmation.",
    note: "Waiting on approval from Lucia.",
    nextContactDate: offset(1),
    status: "open",
    occurredAt: "2026-05-26",
    actor: "Maria Lopez",
  },
];

export const seedAutomationEvents: AutomationEvent[] = [
  {
    id: "a1",
    name: "Quote expiry reminders",
    trigger: "Quote valid-until date approaches",
    action: "Create task and notification for assigned salesperson",
    status: "enabled",
    lastRunAt: offset(0),
    nextRunAt: offset(1),
    generatedTaskId: "t1",
    generatedNotificationId: "n1",
  },
  {
    id: "a2",
    name: "Overdue task alerts",
    trigger: "Task due date is older than today and not completed",
    action: "Create critical alert in central notifications",
    status: "enabled",
    lastRunAt: offset(0),
    nextRunAt: offset(1),
    generatedTaskId: "t2",
    generatedNotificationId: "n2",
  },
  {
    id: "a3",
    name: "Lead workflow qualification",
    trigger: "Partner status changes to lead",
    action: "Create qualification task and workflow history event",
    status: "paused",
    lastRunAt: offset(-1),
    nextRunAt: offset(2),
    generatedTaskId: "t5",
    generatedNotificationId: "n3",
  },
];

export const seedPipelines: SalesPipeline[] = [
  {
    id: "pipeline-default",
    name: "Sales pipeline",
    description: "Default opportunity stages for the CRM.",
    stages: [
      { id: "pipeline-stage-draft", name: "Draft", status: "draft", order: 1 },
      { id: "pipeline-stage-sent", name: "Sent", status: "sent", order: 2 },
      { id: "pipeline-stage-negotiation", name: "Negotiation", status: "negotiation", order: 3 },
      { id: "pipeline-stage-won", name: "Won", status: "won", order: 4 },
      { id: "pipeline-stage-lost", name: "Lost", status: "lost", order: 5 },
    ],
  },
];

export const seedApiConnections: ApiConnectionStatus[] = [
  {
    id: "api1",
    systemName: "SDC Cargo",
    baseUrl: "https://api.sdc-cargo.example",
    status: "connected",
    lastSyncAt: offset(0),
    permissionsSource: "Management software user profile",
    tenantKey: "uy-main",
  },
];
