import type { Quote, QuoteStatus, ReminderRule, SalesTask } from "./types";
import { store, newId } from "./store";
import { DEFAULT_REMINDER_PLAN } from "./quote-utils-defaults";

export { DEFAULT_REMINDER_PLAN };

export function quoteStatusBadge(s: QuoteStatus): {
  variant: "default" | "secondary" | "destructive" | "outline";
  children: string;
  className?: string;
} {
  switch (s) {
    case "won":
      return { variant: "default", children: "Won", className: "bg-emerald-600 hover:bg-emerald-600" };
    case "lost":
      return { variant: "destructive", children: "Lost" };
    case "sent":
      return { variant: "default", children: "Sent" };
    case "negotiation":
      return { variant: "secondary", children: "Negotiation" };
    case "expired":
      return { variant: "outline", children: "Expired" };
    default:
      return { variant: "outline", children: "Draft" };
  }
}

export function isQuoteExpired(q: Quote) {
  if (q.status === "won" || q.status === "lost") return false;
  return new Date(q.validUntil + "T23:59:59").getTime() < Date.now();
}

export function formatMoney(amount: number, currency = "USD") {
  try {
    return new Intl.NumberFormat("en-US", { style: "currency", currency }).format(amount);
  } catch {
    return `${currency} ${amount.toFixed(2)}`;
  }
}

export function recomputeAmount(lines: { quantity: number; unitPrice: number }[]) {
  return lines.reduce((sum, l) => sum + (Number(l.quantity) || 0) * (Number(l.unitPrice) || 0), 0);
}

function addDays(isoDate: string, days: number): string {
  const d = new Date(isoDate + "T00:00:00");
  d.setDate(d.getDate() + days);
  return d.toISOString().slice(0, 10);
}

/** Effective rules: per-quote override if set, otherwise global. */
export function effectiveReminderRules(quote: Quote): ReminderRule[] {
  return quote.reminderRules ?? store.reminderRules();
}

/**
 * Create follow-up tasks for a quote based on its validUntil date and
 * applicable reminder rules (per-quote override or global settings).
 */
export function generateFollowUpTasks(quote: Quote): number {
  if (quote.status === "won" || quote.status === "lost" || quote.status === "expired") return 0;

  const rules = effectiveReminderRules(quote);
  const existing = store.tasks().filter((t) => t.quoteId === quote.id);
  const today = new Date().toISOString().slice(0, 10);
  let created = 0;

  for (const r of rules) {
    const dueDate = addDays(quote.validUntil, r.offset);
    if (dueDate < today) continue;

    const subject = `${r.label} \u00b7 ${quote.number}`;
    if (existing.some((t) => t.subject === subject)) continue;

    const task: SalesTask = {
      id: newId("t"),
      partnerId: quote.partnerId,
      contactId: quote.contactId,
      subject,
      comment: `Auto-generated reminder for quote ${quote.number} (${quote.subject}).`,
      responsibleUser: quote.salesperson,
      salesperson: quote.salesperson,
      createdAt: new Date().toISOString(),
      dueDate,
      dueTime: "09:00",
      priority: r.priority,
      status: "pending",
      contactMethod: "call",
      quoteId: quote.id,
      autoGenerated: true,
    };
    store.upsertTask(task);
    created++;
  }
  return created;
}

/** Identify auto-generated reminder tasks for a quote. */
function isAutoGeneratedQuoteTask(task: SalesTask, quote: Quote): boolean {
  if (task.quoteId !== quote.id) return false;
  if (task.autoGenerated === true) return true;
  // Backward-compat: tasks created before the autoGenerated flag existed.
  if (task.autoGenerated === undefined && task.comment?.startsWith("Auto-generated reminder for quote")) {
    return true;
  }
  return false;
}

function writeTasks(tasks: SalesTask[]) {
  if (typeof window === "undefined") return;
  window.localStorage.setItem("crm.tasks", JSON.stringify(tasks));
  window.dispatchEvent(new CustomEvent("crm:store-change", { detail: "crm.tasks" }));
}

/**
 * Remove existing auto-generated reminder tasks for a quote and recreate them
 * based on the current validUntil date and effective reminder rules.
 * Preserves manually created tasks linked to the quote.
 */
export function regenerateFollowUpTasks(quote: Quote): { removed: number; created: number } {
  const allTasks = store.tasks();
  const kept = allTasks.filter((t) => !isAutoGeneratedQuoteTask(t, quote));
  const removed = allTasks.length - kept.length;

  writeTasks(kept);
  const created = generateFollowUpTasks(quote);
  return { removed, created };
}
