export type PartnerRole = "customer" | "supplier" | "mixed" | "other";
export type PartnerStatus = "active" | "prospect" | "inactive" | "lead";

export interface BankDetail {
  id: string;
  bankName: string;
  accountNumber: string;
  swift?: string;
  currency?: string;
}

export interface Branch {
  id: string;
  name: string;
  address: string;
  type: "branch" | "warehouse";
}

export interface Partner {
  id: string;
  companyName: string;
  tradeName?: string;
  taxId?: string;
  country?: string;
  city?: string;
  state?: string;
  address?: string;
  postalCode?: string;
  phones: string[];
  emails: string[];
  website?: string;
  language?: string;
  status: PartnerStatus;
  salesperson?: string;
  manager?: string;
  notes?: string;
  customText?: string;
  roles: PartnerRole[];
  bankDetails: BankDetail[];
  branches: Branch[];
  createdAt: string;
}

export interface Contact {
  id: string;
  partnerId: string;
  firstName: string;
  lastName: string;
  position?: string;
  email?: string;
  phone?: string;
  whatsapp?: string;
  notes?: string;
}

export type TaskPriority = "low" | "medium" | "high" | "urgent";
export type TaskStatus = "pending" | "in_progress" | "on_hold" | "completed" | "cancelled";
export type ContactMethod = "call" | "whatsapp" | "email" | "social" | "meeting";

export interface SalesTask {
  id: string;
  partnerId?: string;
  contactId?: string;
  email?: string;
  phone?: string;
  subject: string;
  comment?: string;
  responsibleUser: string;
  salesperson: string;
  createdAt: string;
  dueDate: string; // ISO
  dueTime?: string; // HH:mm
  priority: TaskPriority;
  status: TaskStatus;
  contactMethod: ContactMethod;
  quoteId?: string;
  transactionId?: string;
  autoGenerated?: boolean;
  nextContactDate?: string;
}

export interface User {
  id: string;
  name: string;
  email: string;
  role?: string;
  tenantKey?: string;
  permissions?: string[];
  token?: string;
}

export type QuoteStatus = "draft" | "sent" | "negotiation" | "won" | "lost" | "expired";

export interface PipelineStage {
  id: string;
  name: string;
  status: QuoteStatus;
  order: number;
}

export interface SalesPipeline {
  id: string;
  name: string;
  description?: string;
  stages: PipelineStage[];
}

export interface QuoteLine {
  id: string;
  description: string;
  quantity: number;
  unitPrice: number;
}

export interface ReminderRule {
  id: string;
  offset: number; // days relative to validUntil (negative = before)
  priority: TaskPriority;
  label: string;
}

export interface Quote {
  id: string;
  number: string; // e.g. Q-2034
  partnerId: string;
  contactId?: string;
  subject: string;
  status: QuoteStatus;
  currency: string;
  amount: number;
  issueDate: string; // ISO date
  validUntil: string; // ISO date
  salesperson: string;
  notes?: string;
  lines: QuoteLine[];
  createdAt: string;
  /** Per-quote override; when undefined, the global reminder rules apply. */
  reminderRules?: ReminderRule[];
}

export type NotificationType = "alert" | "reminder" | "system" | "workflow";
export type NotificationSeverity = "info" | "warning" | "success" | "critical";

export interface CrmNotification {
  id: string;
  title: string;
  message: string;
  type: NotificationType;
  severity: NotificationSeverity;
  createdAt: string;
  readAt?: string;
  partnerId?: string;
  taskId?: string;
  quoteId?: string;
  assignedTo?: string;
}

export type OperationStatus = "active" | "completed" | "cancelled" | "on_hold";
export type TrafficMode = "air" | "ocean" | "road" | "warehouse";

export interface Operation {
  id: string;
  number: string;
  partnerId: string;
  quoteId?: string;
  trafficMode: TrafficMode;
  origin: string;
  destination: string;
  status: OperationStatus;
  openedAt: string;
  closedAt?: string;
  revenue: number;
  currency: string;
  assignedTo: string;
}

export type InteractionChannel = "email" | "whatsapp" | "call" | "meeting" | "note";
export type InteractionDirection = "inbound" | "outbound" | "internal";

export interface Interaction {
  id: string;
  partnerId: string;
  contactId?: string;
  quoteId?: string;
  taskId?: string;
  channel: InteractionChannel;
  direction: InteractionDirection;
  subject: string;
  body: string;
  occurredAt: string;
  createdBy: string;
}

export type HistoryEventType =
  | "created"
  | "status_change"
  | "quote"
  | "task"
  | "operation"
  | "interaction"
  | "automation";

export interface CustomerHistoryEvent {
  id: string;
  partnerId: string;
  type: HistoryEventType;
  title: string;
  description: string;
  occurredAt: string;
  actor: string;
  quoteId?: string;
  taskId?: string;
  operationId?: string;
}

export interface SalesEvent {
  id: string;
  partnerId: string;
  taskId?: string;
  quoteId?: string;
  contactId?: string;
  kind: string;
  action: string;
  note?: string;
  nextContactDate?: string;
  status?: string;
  occurredAt: string;
  actor: string;
}

export type AutomationStatus = "enabled" | "paused" | "failed";

export interface AutomationEvent {
  id: string;
  name: string;
  trigger: string;
  action: string;
  status: AutomationStatus;
  lastRunAt: string;
  nextRunAt?: string;
  generatedTaskId?: string;
  generatedNotificationId?: string;
}

export interface ApiConnectionStatus {
  id: string;
  systemName: string;
  baseUrl: string;
  status: "connected" | "degraded" | "offline";
  lastSyncAt: string;
  permissionsSource: string;
  tenantKey: string;
  syncMode?: string;
  apiKeyConfigured?: boolean;
}

export interface AuditEvent {
  id: string;
  actorId?: string;
  actorEmail?: string;
  action: string;
  resource: string;
  resourceId?: string;
  occurredAt: string;
  details: Record<string, unknown>;
}
