/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppUsersRouteImport } from './routes/_app/users'
import { Route as AppTasksRouteImport } from './routes/_app/tasks'
import { Route as AppSalesEventsRouteImport } from './routes/_app/sales-events'
import { Route as AppOperationsRouteImport } from './routes/_app/operations'
import { Route as AppNotificationsRouteImport } from './routes/_app/notifications'
import { Route as AppMessagesRouteImport } from './routes/_app/messages'
import { Route as AppIntegrationRouteImport } from './routes/_app/integration'
import { Route as AppHistoryRouteImport } from './routes/_app/history'
import { Route as AppContactsRouteImport } from './routes/_app/contacts'
import { Route as AppAutomationsRouteImport } from './routes/_app/automations'
import { Route as AppAuditRouteImport } from './routes/_app/audit'
import { Route as AppQuotesIndexRouteImport } from './routes/_app/quotes/index'
import { Route as AppPartnersIndexRouteImport } from './routes/_app/partners/index'
import { Route as AppTasksIdRouteImport } from './routes/_app/tasks/$id'
import { Route as AppReportsSalesTraceabilityRouteImport } from './routes/_app/reports/sales-traceability'
import { Route as AppQuotesRemindersRouteImport } from './routes/_app/quotes/reminders'
import { Route as AppQuotesPipelineRouteImport } from './routes/_app/quotes/pipeline'
import { Route as AppQuotesIdRouteImport } from './routes/_app/quotes/$id'
import { Route as AppPartnersIdRouteImport } from './routes/_app/partners/$id'
import { Route as AppOperationsIdRouteImport } from './routes/_app/operations/$id'
import { Route as AppContactsIdRouteImport } from './routes/_app/contacts/$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesEventsRoute = AppSalesEventsRouteImport.update({
  id: '/sales-events',
  path: '/sales-events',
  getParentRoute: () => AppRoute,
} as any)
const AppOperationsRoute = AppOperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationRoute = AppIntegrationRouteImport.update({
  id: '/integration',
  path: '/integration',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppContactsRoute = AppContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AppRoute,
} as any)
const AppAutomationsRoute = AppAutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppQuotesIndexRoute = AppQuotesIndexRouteImport.update({
  id: '/quotes/',
  path: '/quotes/',
  getParentRoute: () => AppRoute,
} as any)
const AppPartnersIndexRoute = AppPartnersIndexRouteImport.update({
  id: '/partners/',
  path: '/partners/',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksIdRoute = AppTasksIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppTasksRoute,
} as any)
const AppReportsSalesTraceabilityRoute =
  AppReportsSalesTraceabilityRouteImport.update({
    id: '/reports/sales-traceability',
    path: '/reports/sales-traceability',
    getParentRoute: () => AppRoute,
  } as any)
const AppQuotesRemindersRoute = AppQuotesRemindersRouteImport.update({
  id: '/quotes/reminders',
  path: '/quotes/reminders',
  getParentRoute: () => AppRoute,
} as any)
const AppQuotesPipelineRoute = AppQuotesPipelineRouteImport.update({
  id: '/quotes/pipeline',
  path: '/quotes/pipeline',
  getParentRoute: () => AppRoute,
} as any)
const AppQuotesIdRoute = AppQuotesIdRouteImport.update({
  id: '/quotes/$id',
  path: '/quotes/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppPartnersIdRoute = AppPartnersIdRouteImport.update({
  id: '/partners/$id',
  path: '/partners/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppOperationsIdRoute = AppOperationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppOperationsRoute,
} as any)
const AppContactsIdRoute = AppContactsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppContactsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/audit': typeof AppAuditRoute
  '/automations': typeof AppAutomationsRoute
  '/contacts': typeof AppContactsRouteWithChildren
  '/history': typeof AppHistoryRoute
  '/integration': typeof AppIntegrationRoute
  '/messages': typeof AppMessagesRoute
  '/notifications': typeof AppNotificationsRoute
  '/operations': typeof AppOperationsRouteWithChildren
  '/sales-events': typeof AppSalesEventsRoute
  '/tasks': typeof AppTasksRouteWithChildren
  '/users': typeof AppUsersRoute
  '/contacts/$id': typeof AppContactsIdRoute
  '/operations/$id': typeof AppOperationsIdRoute
  '/partners/$id': typeof AppPartnersIdRoute
  '/quotes/$id': typeof AppQuotesIdRoute
  '/quotes/pipeline': typeof AppQuotesPipelineRoute
  '/quotes/reminders': typeof AppQuotesRemindersRoute
  '/reports/sales-traceability': typeof AppReportsSalesTraceabilityRoute
  '/tasks/$id': typeof AppTasksIdRoute
  '/partners/': typeof AppPartnersIndexRoute
  '/quotes/': typeof AppQuotesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/audit': typeof AppAuditRoute
  '/automations': typeof AppAutomationsRoute
  '/contacts': typeof AppContactsRouteWithChildren
  '/history': typeof AppHistoryRoute
  '/integration': typeof AppIntegrationRoute
  '/messages': typeof AppMessagesRoute
  '/notifications': typeof AppNotificationsRoute
  '/operations': typeof AppOperationsRouteWithChildren
  '/sales-events': typeof AppSalesEventsRoute
  '/tasks': typeof AppTasksRouteWithChildren
  '/users': typeof AppUsersRoute
  '/': typeof AppIndexRoute
  '/contacts/$id': typeof AppContactsIdRoute
  '/operations/$id': typeof AppOperationsIdRoute
  '/partners/$id': typeof AppPartnersIdRoute
  '/quotes/$id': typeof AppQuotesIdRoute
  '/quotes/pipeline': typeof AppQuotesPipelineRoute
  '/quotes/reminders': typeof AppQuotesRemindersRoute
  '/reports/sales-traceability': typeof AppReportsSalesTraceabilityRoute
  '/tasks/$id': typeof AppTasksIdRoute
  '/partners': typeof AppPartnersIndexRoute
  '/quotes': typeof AppQuotesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/audit': typeof AppAuditRoute
  '/_app/automations': typeof AppAutomationsRoute
  '/_app/contacts': typeof AppContactsRouteWithChildren
  '/_app/history': typeof AppHistoryRoute
  '/_app/integration': typeof AppIntegrationRoute
  '/_app/messages': typeof AppMessagesRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/operations': typeof AppOperationsRouteWithChildren
  '/_app/sales-events': typeof AppSalesEventsRoute
  '/_app/tasks': typeof AppTasksRouteWithChildren
  '/_app/users': typeof AppUsersRoute
  '/_app/': typeof AppIndexRoute
  '/_app/contacts/$id': typeof AppContactsIdRoute
  '/_app/operations/$id': typeof AppOperationsIdRoute
  '/_app/partners/$id': typeof AppPartnersIdRoute
  '/_app/quotes/$id': typeof AppQuotesIdRoute
  '/_app/quotes/pipeline': typeof AppQuotesPipelineRoute
  '/_app/quotes/reminders': typeof AppQuotesRemindersRoute
  '/_app/reports/sales-traceability': typeof AppReportsSalesTraceabilityRoute
  '/_app/tasks/$id': typeof AppTasksIdRoute
  '/_app/partners/': typeof AppPartnersIndexRoute
  '/_app/quotes/': typeof AppQuotesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/audit'
    | '/automations'
    | '/contacts'
    | '/history'
    | '/integration'
    | '/messages'
    | '/notifications'
    | '/operations'
    | '/sales-events'
    | '/tasks'
    | '/users'
    | '/contacts/$id'
    | '/operations/$id'
    | '/partners/$id'
    | '/quotes/$id'
    | '/quotes/pipeline'
    | '/quotes/reminders'
    | '/reports/sales-traceability'
    | '/tasks/$id'
    | '/partners/'
    | '/quotes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/audit'
    | '/automations'
    | '/contacts'
    | '/history'
    | '/integration'
    | '/messages'
    | '/notifications'
    | '/operations'
    | '/sales-events'
    | '/tasks'
    | '/users'
    | '/'
    | '/contacts/$id'
    | '/operations/$id'
    | '/partners/$id'
    | '/quotes/$id'
    | '/quotes/pipeline'
    | '/quotes/reminders'
    | '/reports/sales-traceability'
    | '/tasks/$id'
    | '/partners'
    | '/quotes'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/audit'
    | '/_app/automations'
    | '/_app/contacts'
    | '/_app/history'
    | '/_app/integration'
    | '/_app/messages'
    | '/_app/notifications'
    | '/_app/operations'
    | '/_app/sales-events'
    | '/_app/tasks'
    | '/_app/users'
    | '/_app/'
    | '/_app/contacts/$id'
    | '/_app/operations/$id'
    | '/_app/partners/$id'
    | '/_app/quotes/$id'
    | '/_app/quotes/pipeline'
    | '/_app/quotes/reminders'
    | '/_app/reports/sales-traceability'
    | '/_app/tasks/$id'
    | '/_app/partners/'
    | '/_app/quotes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks': {
      id: '/_app/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales-events': {
      id: '/_app/sales-events'
      path: '/sales-events'
      fullPath: '/sales-events'
      preLoaderRoute: typeof AppSalesEventsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/operations': {
      id: '/_app/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof AppOperationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/messages': {
      id: '/_app/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integration': {
      id: '/_app/integration'
      path: '/integration'
      fullPath: '/integration'
      preLoaderRoute: typeof AppIntegrationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/history': {
      id: '/_app/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contacts': {
      id: '/_app/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AppContactsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/automations': {
      id: '/_app/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AppAutomationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quotes/': {
      id: '/_app/quotes/'
      path: '/quotes'
      fullPath: '/quotes/'
      preLoaderRoute: typeof AppQuotesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/partners/': {
      id: '/_app/partners/'
      path: '/partners'
      fullPath: '/partners/'
      preLoaderRoute: typeof AppPartnersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks/$id': {
      id: '/_app/tasks/$id'
      path: '/$id'
      fullPath: '/tasks/$id'
      preLoaderRoute: typeof AppTasksIdRouteImport
      parentRoute: typeof AppTasksRoute
    }
    '/_app/reports/sales-traceability': {
      id: '/_app/reports/sales-traceability'
      path: '/reports/sales-traceability'
      fullPath: '/reports/sales-traceability'
      preLoaderRoute: typeof AppReportsSalesTraceabilityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quotes/reminders': {
      id: '/_app/quotes/reminders'
      path: '/quotes/reminders'
      fullPath: '/quotes/reminders'
      preLoaderRoute: typeof AppQuotesRemindersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quotes/pipeline': {
      id: '/_app/quotes/pipeline'
      path: '/quotes/pipeline'
      fullPath: '/quotes/pipeline'
      preLoaderRoute: typeof AppQuotesPipelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quotes/$id': {
      id: '/_app/quotes/$id'
      path: '/quotes/$id'
      fullPath: '/quotes/$id'
      preLoaderRoute: typeof AppQuotesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/partners/$id': {
      id: '/_app/partners/$id'
      path: '/partners/$id'
      fullPath: '/partners/$id'
      preLoaderRoute: typeof AppPartnersIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/operations/$id': {
      id: '/_app/operations/$id'
      path: '/$id'
      fullPath: '/operations/$id'
      preLoaderRoute: typeof AppOperationsIdRouteImport
      parentRoute: typeof AppOperationsRoute
    }
    '/_app/contacts/$id': {
      id: '/_app/contacts/$id'
      path: '/$id'
      fullPath: '/contacts/$id'
      preLoaderRoute: typeof AppContactsIdRouteImport
      parentRoute: typeof AppContactsRoute
    }
  }
}

interface AppContactsRouteChildren {
  AppContactsIdRoute: typeof AppContactsIdRoute
}

const AppContactsRouteChildren: AppContactsRouteChildren = {
  AppContactsIdRoute: AppContactsIdRoute,
}

const AppContactsRouteWithChildren = AppContactsRoute._addFileChildren(
  AppContactsRouteChildren,
)

interface AppOperationsRouteChildren {
  AppOperationsIdRoute: typeof AppOperationsIdRoute
}

const AppOperationsRouteChildren: AppOperationsRouteChildren = {
  AppOperationsIdRoute: AppOperationsIdRoute,
}

const AppOperationsRouteWithChildren = AppOperationsRoute._addFileChildren(
  AppOperationsRouteChildren,
)

interface AppTasksRouteChildren {
  AppTasksIdRoute: typeof AppTasksIdRoute
}

const AppTasksRouteChildren: AppTasksRouteChildren = {
  AppTasksIdRoute: AppTasksIdRoute,
}

const AppTasksRouteWithChildren = AppTasksRoute._addFileChildren(
  AppTasksRouteChildren,
)

interface AppRouteChildren {
  AppAuditRoute: typeof AppAuditRoute
  AppAutomationsRoute: typeof AppAutomationsRoute
  AppContactsRoute: typeof AppContactsRouteWithChildren
  AppHistoryRoute: typeof AppHistoryRoute
  AppIntegrationRoute: typeof AppIntegrationRoute
  AppMessagesRoute: typeof AppMessagesRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppOperationsRoute: typeof AppOperationsRouteWithChildren
  AppSalesEventsRoute: typeof AppSalesEventsRoute
  AppTasksRoute: typeof AppTasksRouteWithChildren
  AppUsersRoute: typeof AppUsersRoute
  AppIndexRoute: typeof AppIndexRoute
  AppPartnersIdRoute: typeof AppPartnersIdRoute
  AppQuotesIdRoute: typeof AppQuotesIdRoute
  AppQuotesPipelineRoute: typeof AppQuotesPipelineRoute
  AppQuotesRemindersRoute: typeof AppQuotesRemindersRoute
  AppReportsSalesTraceabilityRoute: typeof AppReportsSalesTraceabilityRoute
  AppPartnersIndexRoute: typeof AppPartnersIndexRoute
  AppQuotesIndexRoute: typeof AppQuotesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAuditRoute: AppAuditRoute,
  AppAutomationsRoute: AppAutomationsRoute,
  AppContactsRoute: AppContactsRouteWithChildren,
  AppHistoryRoute: AppHistoryRoute,
  AppIntegrationRoute: AppIntegrationRoute,
  AppMessagesRoute: AppMessagesRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppOperationsRoute: AppOperationsRouteWithChildren,
  AppSalesEventsRoute: AppSalesEventsRoute,
  AppTasksRoute: AppTasksRouteWithChildren,
  AppUsersRoute: AppUsersRoute,
  AppIndexRoute: AppIndexRoute,
  AppPartnersIdRoute: AppPartnersIdRoute,
  AppQuotesIdRoute: AppQuotesIdRoute,
  AppQuotesPipelineRoute: AppQuotesPipelineRoute,
  AppQuotesRemindersRoute: AppQuotesRemindersRoute,
  AppReportsSalesTraceabilityRoute: AppReportsSalesTraceabilityRoute,
  AppPartnersIndexRoute: AppPartnersIndexRoute,
  AppQuotesIndexRoute: AppQuotesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
